#!/usr/bin/env -S perl -w

use warnings;
use strict;
use v5.28;
use autodie;

use Digest::SHA;

sub slurp { do { local (@ARGV, $/) = shift; <> } }

sub sha512 {
    my $file = shift;
    open my $fh, '<:bytes', $file;
    my $digest = Digest::SHA->new('sha512')->addfile($fh)->digest;
    close $fh;
    return $digest
}

my ($fileA, $fileB) = @ARGV;

if (-s $fileA != -s $fileB) {
    exit 1;
}

exit (sha512($fileA) ne sha512($fileB))
